
name: Node CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - name: Deploy to Server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            script: |
                cd laweb
                git pull
                npm install
                npm run build --if-present
                npm run test --if-present
                pm2 reload laweb
